### ISSUE TITLE
Hey, DronCode got any contact details?

### ISSUE THREAD

**Issue by HHCHunter** [DronCode/ReHitman#1]
Howdy :)

I think I should be able to do a few pull requests and commit to this project, do you happen to have any social media or contact details? I'd really like to help with this project since it's a HUGE dream of mine.

Discord / Slack / Email?

**Comment by DronCode** [comment]
Hi. 
Yes, you can write me a letter to email alexandrleutin@gmail.com or make an issue in this repository.
