### ISSUE TITLE
Setup Automated AppVeyor Builds

### ISSUE THREAD

**Issue by HHCHunter** [DronCode/ReHitman#17]
Since I can't be bothered to compile things with Visual Studio,
This issue is focusing on setting up & using AppVeyor for this project.

Requirements

 - Log into a AppVeyor Account associated with the Project.
 - Sign up with the associated github account via OAuth 
 - Authorize GitHub or BitBucket to list this repo. 
 - Setup the AppVeyor Project for this Project.
	  - Outlined: https://github.com/DronCode/ReHitman/issues/17#issuecomment-584159620
 - Start the Build Process

Benefits

 - Users who don't have access to a compiler can test and use the latest project master, or PR's.
 - We don't have to supply binaries to users.
 - Widened test Audience.
	
Blockers for this Issue

 - Current Visual Studio Project Output  
 - We need to change this from Z: etc etc etc, to something current directory.
 - Will submit PR for.
			
Potential Future Issue for Review

 - Review where we are currently exporting the projects binaries too:
 - PR Artifacts & Continuous Build Delivery

**Comment by HHCHunter** [comment]
Tagging @Notexe

**Comment by HHCHunter** [comment]
Within AppVeyor, we are required to set the following options

Build:
 - Configuration: Debug
 - Platform: x86
 - Visual Studio Solution or Project File: HM3CoreKill\HM3CoreKill.sln
	
Environment:
 - Visual Studio 2019

Artifacts:
 - HM3CoreKill\Debug\Launcher.exe
 - HM3CoreKill\Debug\HM3CoreKill.dll

**Comment by HHCHunter** [comment]
A blocker as well.
https://github.com/DronCode/ReHitman/issues/3#issuecomment-581013942

**Comment by DronCode** [comment]
It was fixed in the master branch. Folder `x86` was renamed to `utils` and .sln project file fixed for it.

**Comment by HHCHunter** [comment]
Associated PR to get this all working #18

**Comment by HHCHunter** [comment]
PR Merged, @DronCode Required to do AppVeyor side stuff for this project.
Once done we will have automated builds!

Instructions for AppVeyor setup:
https://github.com/DronCode/ReHitman/issues/17#issuecomment-584159620

Will close once done

**Comment by DronCode** [comment]
Badge & AppVeyor integration works : )

**Comment by HHCHunter** [comment]
Closing issue
