### ISSUE TITLE
Disable keyboard & mouse input when debug menu opened

### ISSUE THREAD

**Issue by DronCode** [DronCode/ReHitman#19]
It's very difficult to use the debug menu when keyboard & mouse input enabled.
Too many conflicts in work.
As a solution, we can hook the update method on the keyboard and stop mouse events emitting when the in-game debugger opened.

**Comment by DronCode** [comment]
Can be fixed in #27 (found in-game events, through that we can disable player input if it needed).
@HHCHunter, @Notexe what do you feel about it?

**Comment by HHCHunter** [comment]
I think it's a good idea, as long as we can notify the player that this is the case.
Should be possible in imGUI

**Comment by DronCode** [comment]
If ReHitman debugger is opened player will get the event "MSG_DISABLECONTROLS". 
If debugger closed the player will get event "MSG_ENABLECONTROLS".

**Comment by Notexe** [comment]
Nice, that should work.
