### ISSUE TITLE
x86 directory not included

### ISSUE THREAD

**Issue by Notexe** [DronCode/ReHitman#3]
I wanted to compile this to test it out but you haven't included the x86 directory for HM3CoreKill, just thought I would let you know.

**Comment by DronCode** [comment]
Hi. Yes, it's a known issue.
For now, I little busy and could not upload fixes. 
In the last PR I forgot about that. Will be fixed as soon as possible :)
Stay tuned, or give me your email and I'll send the last version of source code directly to you)

**Comment by Notexe** [comment]
Hey, thanks for getting back to me. My email is joshuadodd1107@gmail.com if you do wish to send the latest source to me. This is a pretty interesting project so far and I'm glad that it's a thing. Thank you.

**Comment by DronCode** [comment]
Done :)
The latest archive is here https://drive.google.com/file/d/1bO4o23ZwAMQT9pzRC1DZOcGxJfrukoGk/view

**Comment by DronCode** [comment]
x86 folder was excluded from project by gitignore file. 
I'll fix that later via renaming of x86 to utils
