### ISSUE TITLE
ZIP Free File System | Issues

### ISSUE THREAD

**Issue by DronCode** [DronCode/ReHitman#31]
If you have any problems with ZIP Free File System create issues for it and link it to this issue.

**Documentation**: [ZIP Free File System](https://github.com/DronCode/ReHitman/wiki/ZIP-Free-File-System)

**Comment by DronCode** [comment]
**Tested on** https://github.com/DronCode/ReHitman/pull/27/commits/3f1ba2ed0936a032c0ba817d1b83c8e8e9df912f

**Checked**:

1. HitmanBloodMoney
2. HideOut
3. M00
4. M01
5. M02
6. M03
7. M13

**Comment by HHCHunter** [comment]
I've checked You Better Watch Out, no issues.
M07

**Comment by HHCHunter** [comment]
I've tested most levels, I think this can be closed.

**Comment by DronCode** [comment]
Good
