### ISSUE TITLE
Move docs to wiki

### ISSUE THREAD

**Issue by DronCode** [DronCode/ReHitman#35]
We have a few notes in the folder 
`HM3CoreKill/HM3CoreKill/docs/`
and I guess it's better been in wiki pages.

**Comment by HHCHunter** [comment]
Done

INI
- github.com/DronCode/ReHitman/blob/master/HM3CoreKill/HM3CoreKill/docs/INIArgs.md
- github.com/DronCode/ReHitman/wiki/HitmanBloodMoney.ini

Mission Scripts
- github.com/DronCode/ReHitman/edit/master/HM3CoreKill/HM3CoreKill/docs/MissionScripts.md
- github.com/DronCode/ReHitman/wiki/MissionScripts.md
